name: Go

on:
  release:
    types: [created, edited]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - name: Check out code
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go mod tidy 
        go mod vendor

    - name: Test
      run: go test -v -count=1 -race ./...
      
    - name: Build
      run: |
        env CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -ldflags "-X main.Version=${{ github.ref }}" -mod vendor -o ./dist/eventmaker ./cmd
        env CGO_ENABLED=0 GOOS=linux   GOARCH=amd64 go build -ldflags "-X main.Version=${{ github.ref }}" -mod vendor -o ./dist/eventmaker-linux ./cmd
        env CGO_ENABLED=0 GOOS=darwin  GOARCH=amd64 go build -ldflags "-X main.Version=${{ github.ref }}" -mod vendor -o ./dist/eventmaker-windows.exe ./cmd

